---
title: "rRNADepletion_s4ter"
subtitle: "k-mer analysis"
author: "Lachlan Baer"
date-modified: today
date-format: "DD MMMM, YYYY"
modified-title: "LAST MODIFIED"
code-fold: true
fig-width: 8
fig-height: 6
fig-align: center
editor_options:
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
    echo = TRUE,
    message = FALSE,
    warning = FALSE,
    error = FALSE,
    fig.align = "center"
)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

# Setup 

```{r packages}
library(tidyverse)
library(magrittr)
library(parallel)
library(pander)
library(here)
library(scales)
library(ggpubr)
library(kableExtra)
library(edgeR)
library(DT)
library(ggrepel)
library(pheatmap)
library(ggdendro)
library(RColorBrewer)
library(ggtext)
library(glue)
library(patchwork)
```

```{r options}
if (interactive()) setwd(here::here())
theme_set(theme_bw())
theme_update(
    axis.title.x = element_markdown(),
    axis.title.y = element_markdown(),
)
```

```{r}
pal <- brewer.pal(8, "Set2")
```

# Load data

```{r}
k5counts <- readRDS(here("1_Psen2S4Ter/Rdata/k5counts.Rds"))
k6counts <- readRDS(here("1_Psen2S4Ter/Rdata/k6counts.Rds"))
k7counts <- readRDS(here("1_Psen2S4Ter/Rdata/k7counts.Rds"))
k8counts <- readRDS(here("1_Psen2S4Ter/Rdata/k8counts.Rds"))
k9counts <- readRDS(here("1_Psen2S4Ter/Rdata/k9counts.Rds"))
k10counts <- readRDS(here("1_Psen2S4Ter/Rdata/k10counts.Rds"))
k11counts <- readRDS(here("1_Psen2S4Ter/Rdata/k11counts.Rds"))
k12counts <- readRDS(here("1_Psen2S4Ter/Rdata/k12counts.Rds"))
```

```{r}
k5topTable <- readRDS(here("1_Psen2S4Ter/Rdata/k5topTable.Rds"))
k6topTable <- readRDS(here("1_Psen2S4Ter/Rdata/k6topTable.Rds"))
k7topTable <- readRDS(here("1_Psen2S4Ter/Rdata/k7topTable.Rds"))
k8topTable <- readRDS(here("1_Psen2S4Ter/Rdata/k8topTable.Rds"))
k9topTable <- readRDS(here("1_Psen2S4Ter/Rdata/k9topTable.Rds"))
k10topTable <- readRDS(here("1_Psen2S4Ter/Rdata/k10topTable.Rds"))
k11topTable <- readRDS(here("1_Psen2S4Ter/Rdata/k11topTable.Rds"))
k12topTable <- readRDS(here("1_Psen2S4Ter/Rdata/k12topTable.Rds"))
```

# kappa vs lfc

```{r}
kappa_k5 <- readRDS(here("1_Psen2S4Ter/Rdata/kappa_k5.Rds"))
kappa_k6 <- readRDS(here("1_Psen2S4Ter/Rdata/kappa_k6.Rds"))
kappa_k7 <- readRDS(here("1_Psen2S4Ter/Rdata/kappa_k7.Rds"))
kappa_k8 <- readRDS(here("1_Psen2S4Ter/Rdata/kappa_k8.Rds"))
kappa_k9 <- readRDS(here("1_Psen2S4Ter/Rdata/kappa_k9.Rds"))
kappa_k10 <- readRDS(here("1_Psen2S4Ter/Rdata/kappa_k10.Rds"))
kappa_k11 <- readRDS(here("1_Psen2S4Ter/Rdata/kappa_k11.Rds"))
kappa_k12 <- readRDS(here("1_Psen2S4Ter/Rdata/kappa_k12.Rds"))
```

```{r}
res_g_k5 <- readRDS(here("1_Psen2S4Ter/Rdata/res_g_k5.Rds"))
res_g_k6 <- readRDS(here("1_Psen2S4Ter/Rdata/res_g_k6.Rds"))
res_g_k7 <- readRDS(here("1_Psen2S4Ter/Rdata/res_g_k7.Rds"))
res_g_k8 <- readRDS(here("1_Psen2S4Ter/Rdata/res_g_k8.Rds"))
res_g_k9 <- readRDS(here("1_Psen2S4Ter/Rdata/res_g_k9.Rds"))
res_g_k10 <- readRDS(here("1_Psen2S4Ter/Rdata/res_g_k10_abs.Rds"))
res_g_k11 <- readRDS(here("1_Psen2S4Ter/Rdata/res_g_k11.Rds"))
res_g_k12 <- readRDS(here("1_Psen2S4Ter/Rdata/res_g_k12.Rds"))
```

```{r}
tt_g <- readRDS(here("1_Psen2S4Ter/Rdata/tt_g.Rds"))
```

```{r}
plot_lfc_kappa <- function(kappa, k){
    lapply(tt_g, \(x){
        kappa %>%
            enframe(name = "Geneid", value = "kappa") %>%
            left_join(x[,c("Geneid", "logFC", "coef")]) %>%
            mutate(
                coef = str_remove(coef, "group")
            )
    }) %>%
        bind_rows() %>%
        ggplot(aes(kappa, logFC)) +
        geom_point(shape = 21, fill = "grey20", alpha = 0.4, size = 2) +
        facet_wrap(~coef) +
        labs(
            x = paste0("*\u03ba~g~* (*k* = ", k, ")")
        ) +
        theme(
            text = element_text(size = 20),
            axis.text.x = element_blank(),
            axis.ticks.x = element_blank(),
        )
}
```

```{r}
lfc_k5 <- plot_lfc_kappa(kappa_k5, "5")
lfc_k6 <- plot_lfc_kappa(kappa_k6, "6")
lfc_k7 <- plot_lfc_kappa(kappa_k7, "7")
lfc_k8 <- plot_lfc_kappa(kappa_k8, "8")
lfc_k9 <- plot_lfc_kappa(kappa_k9, "9")
lfc_k10 <- plot_lfc_kappa(kappa_k10, "10")
lfc_k11 <- plot_lfc_kappa(kappa_k11, "11")
lfc_k12 <- plot_lfc_kappa(kappa_k12, "12")
```

```{r}
lfc_k5 +
    lfc_k6 +
    lfc_k7 +
    lfc_k8 +
    lfc_k9 +
    lfc_k10 +
    lfc_k11 +
    lfc_k12 +
    plot_layout(ncol = 2, guides = "collect") +
    # plot_annotation(tag_levels = "A") &
    theme(
        legend.position = "bottom",
        plot.margin = unit(c(.2, .5, .2, .2), "cm"),
        text = element_text(size = 20)
    ) &
    guides(colour = guide_legend(nrow = 1, byrow = TRUE))
ggsave("~/phd/thesis/tex/fig/rRNA/lfc_kappa.png", width = 12, height = 16)
```

# Session info

```{r seshInfo}
sessionInfo()
```